### ISSUE TITLE
Navigare\SSR\HttpGateway::dispatch(): Argument #2 ($page) must be of type Navigare\View\Page, array given

### ISSUE THREAD

**Issue by sparkison** [navigarejs/framework#6]
### Versions:

- `@navigare/core` version: 1.0.100
- `@navigare/vue3` version: 1.0.137

PHP 8.1.0
Laravel 9.43.0

### Describe the problem:

Unable to load in browser, receiving the following error when attempting:
`Navigare\SSR\HttpGateway::dispatch(): Argument #2 ($page) must be of type Navigare\View\Page, array given`

Line highlighted as being the culprit:
`<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" @navigare('htmlAttrs')>`

Stack trace here: https://flareapp.io/share/pPv12vYm#F1

NOTE: this is being added to an existing app with Inertia implementation that has been removed and replaced with Navigare. I don't think that has anything to do with it, but wanted to mention in case there are any additional things that may be required for that

### Steps to reproduce:

Follow documentation installation steps for Server installation and attempt to load app in web browser.

**Comment by jaulz** [comment]
Hm, did you update the Composer package to the latest version? You could try to turn off SSR for the time being by setting this option to false:
https://github.com/navigarejs/framework/blob/98facaf75f0ab2d0656400532e5dd72976106fdf/packages/laravel/config/navigare.php#L18

I will check it in Monday and see if I can reproduce the issue.

**Comment by sparkison** [comment]
I do have the SSR option on the navigare config set to false, so not sure why it's throwing an SSR error? Let me know if you have any other suggestions, or need more input from me.

**Comment by jaulz** [comment]
When did you install the library first? Can you try to clear the cache `php artisan view:clear`? Maybe the old directive is still cached.

**Comment by jaulz** [comment]
Ah, now I saw what the issue is. Inertia and Navigare are both setting `$page` on the view. Inertia sets it as an array but Navigare uses an instance of `Page` class. That's causing the dump... If you want to use Navigare you won't be able to use Inertia as well.

**Comment by sparkison** [comment]
It was installed this past Friday afternoon (2022-12-09). I did clear my local Redis store completely (used for jobs and caching) and also ran artisan view and cache clear, still showing the error.

**Comment by sparkison** [comment]
> Ah, now I saw what the issue is. Inertia and Navigare are both setting `$page` on the view. Inertia sets it as an array but Navigare uses an instance of `Page` class. That's causing the dump... If you want to use Navigare you won't be able to use Inertia as well.

Oh, gotcha! I removed all instances of Inertia ...I thought! Let me see if I can find any traces I might have missed

**Comment by jaulz** [comment]
You can check the stracktrace of your shared error report. There are two appearances:
- vendor/inertiajs/inertia-laravel/src/Response.php
- vendor/laravel/jetstream/src/Http/Middleware/ShareInertiaData.php

**Comment by sparkison** [comment]
I'm using [Laravel Spark](https://spark.laravel.com/) for this particular project, which uses Inertia.js to render the billing portal. Is it possible to use this library in conjunction with Laravel Spark? Wondering if maybe that's causing some issues...

**Comment by sparkison** [comment]
> You can check the stracktrace of your shared error report. There are two appearances:
> 
> * vendor/inertiajs/inertia-laravel/src/Response.php
> * vendor/laravel/jetstream/src/Http/Middleware/ShareInertiaData.php

Oh, bummer, so many things tied to Inertia, lol! 🤣 ...since I'm using[Jetstream](https://jetstream.laravel.com/2.x/introduction.html), it has two options:

1. Livewire
2. Inertia

Any ideas? Looking like I'm going to have to bypass the Jetstream middleware and manually share the data it's looking for via the Nabvigare middleware...

**Comment by jaulz** [comment]
Hm, I see two options:
1. Either you drop Inertia completely and replace this middleware with a Navigare middleware: https://github.com/laravel/jetstream/blob/2.x/stubs/inertia/app/Http/Middleware/HandleInertiaRequests.php
2. You could use two different blade views: one for Inertia and one with Navigare. Though, I think that makes things more complicated going forward.

The former is the way that I also went when I noticed that Inertia lacks a lot of features that I was looking for.

**Comment by sparkison** [comment]
> Hm, I see two options:
> 
> 1. Either you drop Inertia completely and replace this middleware with a Navigare middleware: https://github.com/laravel/jetstream/blob/2.x/stubs/inertia/app/Http/Middleware/HandleInertiaRequests.php
> 2. You could use two different blade views: one for Inertia and one with Navigare. Though, I think that makes things more complicated going forward.
> 
> The former is the way that I also went when I noticed that Inertia lacks a lot of features that I was looking for.

Option one is done, I've removed the Inertia middleware from the app. I think it's being pulled in by Jetstream, or maybe Laravel Spark? But Laravel Spark generates its own page and billing portal (it works like option 2), so I don't think it has an effect on the base-app. 

That said, I'm thinking it's down to Jetstream 🤔

**Comment by jaulz** [comment]
You could try to disable the middleware by changing the `middleware` property with a dummy value:
https://github.com/laravel/jetstream/blob/2.x/config/jetstream.php

**Comment by sparkison** [comment]
> You could try to disable the middleware by changing the `middleware` property with a dummy value: https://github.com/laravel/jetstream/blob/2.x/config/jetstream.php

Had to go a bit deeper, looks like when the "inertia" stack is used, it looks like the Inertia functionality is called here: https://github.com/laravel/jetstream/blob/2.x/src/JetstreamServiceProvider.php#L230 and I'd need to change the stack to an empty value so it doesn't get called here: https://github.com/laravel/jetstream/blob/2.x/src/JetstreamServiceProvider.php#L93-L95

We'll see how this goes! I have a custom middleware added to replace the Jetstream one, and pulling in the JetstreamServiceProvider inertia specific content to my own apps ServiceProvider, modified to share with Navigare 🤞

**Comment by jaulz** [comment]
Great, good luck, let me know how it works out 😊

**Comment by sparkison** [comment]
So I think the long and short is that this framework just isn't compatible with Laravel Jetstream, for anyone else coming across this 😉 

I though it might be an easy swap for Inertia, but Jetstream is deeply integrate with the frameworks it supports, so without forking the Laravel Jetstream library, there's not an easy path. The deeper I dug, the deeper the integration withe specific frameworks (e.g. Inertia or Livewire).

That said, thank you for your work on this! But it's going to be a little more work than I signed up for, so maybe for the next project...
