### ISSUE TITLE
mountApp.ts - TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by sparkison** [navigarejs/framework#7]
### Versions:

- `@navigare/core` version: 1.0.100
- `@navigare/vue3` version: 1.0.137

### Describe the problem:

Unable to mount app, received following error:
`TypeError: Right-hand side of 'instanceof' is not an object`

Code flagged as causing the fuss `mountApp.ts`:
```JS
import { App } from './types'

export default async function mountApp({ id, root }: App): Promise<void> {
  root.mount(`#${id}`)
}
```

### Steps to reproduce:

Add to existing Laravel JS app (not using TS) and attempt to compile and build.

**Comment by jaulz** [comment]
Can you please share your `client.ts` and `createApp.ts` files? See https://navigarejs.github.io/framework/guide/installation/client.html

**Comment by jaulz** [comment]
Hm, I think it could be caused by this line:
```javascript
window.route = route
```

This is actually not possible because `route` is not a variable that you can pass around. It will be replaced at compile time with the respective route details. For the same reason you cannot use variables `route(routeName)` and instead you need to use a fixed route name `route('home.index')`.

Except for that I cannot see anything wrong at first sight...

**Comment by sparkison** [comment]
> Hm, I think it could be caused by this line:
> 
> ```js
> window.route = route
> ```
> 
> This is actually not possible because `route` is not a variable that you can pass around. It will be replaced at compile time with the respective route details. For the same reason you cannot use variables `route(routeName)` and instead you need to use a fixed route name `route('home.index')`.
> 
> Except for that I cannot see anything wrong at first sight...

Commented out and still the same 🤷

**Comment by jaulz** [comment]
Any chance to share the repository with me?

**Comment by sparkison** [comment]
I'll have to check, in the meantime, here's the full JS log in hopes it will help:

```
Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not an object
    at assertType (runtime-core.esm-bundler.js:4143:17)
    at validateProp (runtime-core.esm-bundler.js:4104:45)
    at validateProps (runtime-core.esm-bundler.js:4080:9)
    at initProps (runtime-core.esm-bundler.js:3770:9)
    at setupComponent (runtime-core.esm-bundler.js:7198:5)
    at mountComponent (runtime-core.esm-bundler.js:5524:13)
    at processComponent (runtime-core.esm-bundler.js:5499:17)
    at patch (runtime-core.esm-bundler.js:5101:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5638:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
assertType @ runtime-core.esm-bundler.js:4143
validateProp @ runtime-core.esm-bundler.js:4104
validateProps @ runtime-core.esm-bundler.js:4080
initProps @ runtime-core.esm-bundler.js:3770
setupComponent @ runtime-core.esm-bundler.js:7198
mountComponent @ runtime-core.esm-bundler.js:5524
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
render2 @ runtime-core.esm-bundler.js:6260
mount @ runtime-core.esm-bundler.js:4456
app.mount @ runtime-dom.esm-bundler.js:1607
mountApp @ mountApp.ts:4
(anonymous) @ client.js:4
```

**Comment by jaulz** [comment]
So it's actually about prop type validation. The easiest for you would be to set a breakpoint in `runtime-core.esm-bundler.js:4143:17` and see which prop it's about. If you check the context you will easily see which component the prop belongs to.

**Comment by sparkison** [comment]
Here's what I got:
<img width="1059" alt="Screenshot 2022-12-14 at 9 44 20 AM" src="https://user-images.githubusercontent.com/4400104/207655983-ffb59103-8af5-4dd2-8d36-721b94cbaac1.png">

And down the stack a bit further, looks like it might be the `layout` prop that is undefined:
<img width="1056" alt="Screenshot 2022-12-14 at 9 46 06 AM" src="https://user-images.githubusercontent.com/4400104/207656415-953d3631-6d46-4a4e-97d7-6ca27fbe61f7.png">

**Comment by sparkison** [comment]
Alright, made it a bit further! Looks like the base layout is required, even though the docs say otherwise: https://navigarejs.github.io/framework/guide/basics/layouts.html

After defining a layout, I was able to at least get the app to mount 🎉 
I have some other issues going on, but believe it's related to the previous Inertia integration, so I'll continue to chip away at it...

Feel free to close as I think the undefined layout was ultimately the issue. It may still be an open issue pending confirmation, but it appears a layout is indeed required 😉

**Comment by jaulz** [comment]
Thanks for pointing it out! Now it should work with the default layout as well.
